import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  docsSidebar: [  // This ID *must* match the sidebarId in docusaurus.config.js
    {
      type: 'doc',
      id: 'index', // Corresponds to docs/index.mdx
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'getting-started',
      label: 'Getting Started',
    },
    {
      type: 'category',
      label: 'Authentication',
      items: [
        'authentication/overview',
        'authentication/registration',
        'authentication/login',
        'authentication/forgot-password',
        'authentication/reset-password',
        'authentication/email-verification',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/auth-context',
        'api/actions',
      ],
      collapsed: false,
    },
    'best-practices',
    'troubleshooting',
    'contributing',
  ],
};

export default sidebars;
